name: Security Audit

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  security_audit:
    name: Cargo Audit (RustSec CVEs)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Cargo Audit against RustSec Advisory Database
        uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
